### ISSUE TITLE
Update TWE document template to fix print formatting issue

### ISSUE THREAD

**Issue by cbutcher318** [hackforla/internship#356] opened 2023-02-13 18:57 UTC
### Overview
We need to update the project document template so that headers/footers properly print.

### Action Items
- [x] Review the sample printout of current template with circled issue (resource 1.01)
#### Update Figma 
- [x] Open Internship Figma "Letter & Report Templates" (resource 1.02)
- [x] Copy the "Letter & Report Templates" Figma
- [x] In your copy, edit "Report" and "Letterhead" Figmas for proper print formatting
- [x] Save your copy
- [x] Update Resource `2.01 Updated Figma Copy` link
    1. Choose "Copy Link"
    2. Edit this issue
    3. Update Resources # 2.01 by pasting the link inside the parentheses at the end of the line 
    4. Choose 'Update comment'
#### Create Test Docs
- [x] create a copy of "Letterhead" template (resource 1.03)
- [x] on the Letterhead template, replace the current footer with the updated Figma version
- [x] "Print to PDF" to check if updated footer formatting is printer safe
    1. Choose "File" > "Print"
    2. Choose "Destination" as "Save as PDF"
    3. Preview the generated PDF to check if footer formatting is printer safe (if not, go to "Update Figma" section above and repeat steps to update and test the footer format)
- [x] move your edited copy into "Communication Guide", "Templates" folder
    1. Choose File > Move (or Move icon)
    2. Choose the back arrow to access all your drives
    3. Choose Shared drives > Internships > Internships > Communications Guide > Templates
    4. Choose "Move here"
    5. Choose "Move" when it asks if you want to change ownership to a shared drive
    6. Dismiss the notification that says the file is now in the shared drive
- [x] Update Resource `2.02 copy of Letterhead Template` link
    1. Choose "Share" button in your copy of the letterhead template
    4. Choose "Copy Link"
    5. Edit this issue
    6. Update Resources # 2.02 by pasting the link inside the parentheses at the end of the line 
    7. Choose 'Update comment'
- [x] create a copy of "Report" template (resource 1.04)
- [x] on the Report template, replace the current footer with the updated Figma version
- [x] "Print to PDF" to check if updated footer formatting is printer safe
    1. Choose "File" > "Print"
    2. Choose "Destination" as "Save as PDF"
    3. Preview the generated PDF to check if footer formatting is printer safe (if not, go to "Update Figma" section above and repeat steps to update and test the footer format)
- [x] move your edited copy into "Communication Guide", "Templates" folder
    1. Choose File > Move (or Move icon)
    8. Choose the back arrow to access all your drives
    9. Choose Shared drives > Internships > Internships > Communications Guide > Templates
    10. Choose "Move here"
    11. Choose "Move" when it asks if you want to change ownership to a shared drive
    12. Dismiss the notification that says the file is now in the shared drive
- [x] Update Resource `2.03 copy of Report Template` link
    1. Choose "Share" button in your copy of the letterhead template
    2. Choose "Copy Link"
    3. Edit this issue
    4. Update Resources # 2.03 by pasting the link inside the parentheses at the end of the line 
    5. Choose "Update comment"
- [ ] Send current document PDFs to PM team to print test
- [ ] Product sign-off

#### Resources for Creating the Issue
1.01 - ![TWE template printouts](https://user-images.githubusercontent.com/118405499/219224305-75cf46d7-185b-4aa1-8dae-2ececc05e07b.jpg)
1.02 [Letter & Report Templates Figma](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A35&t=2eT84NEYF61ecooe-0)
1.03 - [Letterhead Template](https://docs.google.com/document/d/1_VHFlyJTXOI628GCymnKE6UBoILK50WHHKUV-nBdBMQ/template/preview)
1.04 - [Report Template](https://docs.google.com/document/d/16GP2QU_41dOBBadLUxEurdHh3FjzbkRMKTScr66pSIQ/template/preview)
1.05 [Communication Guide > Templates Google Drive Folder](https://drive.google.com/drive/folders/1dzYpEI8I3xgHvLVy2-L6NOK2bbMG_T6O)

#### Resources Created during this issue
2.01 [[Updated Figma Copy](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A35)]
2.02 [[copy of Letterhead Template](https://docs.google.com/document/d/1gUvFMXa5dx80shC_INhZ3et22XbqcJkrOROglaQWW4c/edit?usp=sharing)]
2.03 [[copy of Report Template](https://docs.google.com/document/d/1moY_H65EIzD0tr6lbJ0cZLdrNLtFViy_R48ehqR8vVM/edit?usp=sharing)]

**Comment by cbutcher318** [comment] 2023-02-15 18:56
Change instructions to make change in figma and then put footer into blank document for testing

**Comment by RobinElayn** [comment] 2023-02-23 05:43
I printed both the Letterhead and Report templates without any issues of cutoff. Could you please review them and share your feedback? Additional formatting options can be found in the Letter and Report Page Layouts section of Figma. Unfortunately, I couldn't make a complete copy of the page, but I did add a section to the right of the original within the file.

**Comment by ExperimentsInHonesty** [comment] 2023-02-23 20:51
The font got smaller as well as stacked and now there is too much space under the logo and text.

**Comment by ExperimentsInHonesty** [comment] 2023-03-02 19:05
![IMG_4061](https://user-images.githubusercontent.com/37763229/222526935-2d388d58-e69b-4fff-bd66-acd712f6433a.jpg)

**Comment by cbutcher318** [comment] 2023-03-02 19:12
@RobinElayn See picture of printed letter template. To fix:
   - move footer and "Hack for LA..." text to the left so it's not being cut off (~.25" should be good, but use your judgement)
![IMG_4061](https://user-images.githubusercontent.com/37763229/222526935-2d388d58-e69b-4fff-bd66-acd712f6433a.jpg)

When ready, update the "report template" to match

**Comment by RobinElayn** [comment] 2023-03-06 18:36
I moved text and footer & updated Letterhead Template link. This is what the print preview in Letter format looks like on my end. If it is still printing incorrectly, we may need to pass this issue on to someone with a working printer so they can troubleshoot more efficiently. 
![image](https://user-images.githubusercontent.com/124115511/223200364-d605edf7-fa19-4c45-85de-e4091bcd9740.png)

**Comment by cbutcher318** [comment] 2023-03-06 19:19
@RobinElayn 
Print tested and looks great. Update the report template to match when you can and then we can close this out.
Thanks for keeping up with this.

**Comment by RobinElayn** [comment] 2023-03-07 06:16
@cbutcher318 
Report template updated :)

**Comment by priyatalwar** [comment] 2023-03-15 19:03
@RobinElayn if the issue is complete and product has signed off, please feel free to close it. Thanks!

**Closed** 2023-03-16 17:02 UTC
Labels: role: UI/UX design, feature: external communication, size: 0.50pt, Participant Type: TWE Team Member
