### ISSUE TITLE
TWE: Research: Transcription Software Comparison

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#629] opened 2024-10-10 18:03 UTC
### Overview
We need to compile a list of preferred transcription software services and compare their costs, allowed transcript quantity, transcription quality, etc.

### Action Items
- [x] Use `TWE: Template: Spreadsheet`(linked in Resources 1.01) to create a new spreadsheet 
- [x] Rename the spreadsheet as `TWE: Research: Transcription Software Comparison`
- [x] Save the spreadsheet in the Guides and How-Tos folder
     - The path is Internship > Internships > Research > Guides and How-Tos 
- [x] In Resources # 2.01, copy and paste the URL of the spreadsheet between parentheses at the end of the line with no space in between the right bracket `]` and the left parenthesis `(`, so it turns into a hyperlink
- [x] Use the newly created spreadsheet to document transcription software/services and its pros and cons
     - Do some research on the transcription software, and list out at least 5 transcription software commonly used by researchers
     - Use one row for a software or software tier. For example, Otter.ai has basic, pro, business, and enterprise
     - Use one column for a factor in the spreadsheet
         - Factors we should consider but not limited to: costs per month; how many transcripts or minutes are allowed; transcription quality (based on reviews or personal experience), etc.
         - Add other factors you deem important 
- [x] List out the name and URL of the transcription software you compared in `Resources gathered during the completion of the issue` section 
- [x] If further trial is needed, please use a personal email account, not internship or internship-ux Gmail account even if you have access to them
- [x] Summary your findings in comments in this issue
- [x] Review with UXR Leads 
- [ ] Review with Project Lead

#### Resources for creating this issue
1.01 [TWE: Template: Spreadsheet](https://docs.google.com/spreadsheets/d/1yK7U_waj1xfx3KcdQ10uyaLvWCSVVpqLMLHvWonDWL4/template/preview)

#### Resources gathered during the completion of the issue
2.01 [TWE: Research: Transcription Software Comparison](https://docs.google.com/spreadsheets/d/1i9hhAzuf6jJNVeAMcjFaxDyC-PE1ImNHpeK002NouSk/edit?gid=0#gid=0)
2.02 [Otter.ai/Basic](https://otter.ai/pricing)
2.03 [Otter.ai/Pro](https://otter.ai/pricing)
2.04 [Otter.ai/Business](https://otter.ai/pricing)
2.05 [TurboScribe/Free](https://turboscribe.ai/#pricing)
2.06 [TurboScribe/Unlimited](https://turboscribe.ai/#pricing)
2.07 [Condens/Individual](https://condens.io/pricing/)
2.08 [Condens/Team](https://condens.io/pricing/)
2.09 [MeetGreek/Business](https://meetgeek.ai/pricing)
2.10 [Userbit/Free](https://userbit.com/pricing)
2.11 [transcription software samples folder](https://drive.google.com/drive/folders/1nLbv8lsw0sb61Hq2QEVS6A0fZXTTf4v-?usp=drive_link)
2.12 [RP012 Intern I005 Interview Recording Transcript - TurboScribe](https://drive.google.com/file/d/1hHUsVpy46vyj_2lxQH5SWAsEwHoUP9HY/view?usp=drive_link) 
2.13 [RP012 Intern I005 Interview Recording Transcript - Otter](https://drive.google.com/file/d/1B-6pRnnb0QmbGNadHe7Nv4J3uhvUuHld/view?usp=drive_link)

**Comment by pandanista** [comment] 2024-10-10 18:45
@mh-faraji I am assigning this issue to you to research on the transcription software that the org could adopt. Let me know if you have any questions. Thank you.

**Comment by pandanista** [comment] 2024-10-10 18:55
@mh-faraji: Another team member, @kevinmoutoucarpin, suggested [condens.io](https://condens.io/pricing/). Let's look into that. 

@kevinmoutoucarpin Thank you for suggesting Condens.

**Comment by mh-faraji** [comment] 2024-10-10 22:13
@pandanista I believe Otter.ai/Business offers the best value, with unlimited imports and transcriptions of audio or video files at a reasonable monthly price ($30 monthly). Another option could be Turboscribe.ai/Unlimited ($20 monthly) if we have 50 files or fewer. Other software, like GoTranscript, Vook.ai, and Sonix, follow a per-minute or pay-as-you-go pricing model, which can become costly.

**Comment by pandanista** [comment] 2024-10-10 23:42
@mh-faraji Thank you for looking into this. Let's go over those options in a bit more depth next Tuesday before the Thursday all team meeting.

**Comment by pandanista** [comment] 2024-10-15 20:29
Kevin suggested two more tools:
"For the transcription tools, you can also add :
- [MeetGeek](https://meetgeek.ai/pricing) : Free plan includes 5 hours of transcription/month, 3 month transcript storage and 1 month audio storage
- [UserBit](https://userbit.com/pricing) : Free for your first project so it might be possible to upload all your audio/videos and get them transcribed for free as long as you don’t create a 2nd project. At least that’s how I understood. Plus, you can add unique words or phrases to leverage improved accuracy.
You should also look at how each of these tools process data in terms of privacy and security (it's best if you can upload audios/videos without PIIs)"

One more factor we need to consider if we haven't already: Can the transcription or other files be downloaded and saved into our Google drive by using each of the transcription software/tools? We want to make sure we own the transcripts, not the software provider.

**Comment by pandanista** [comment] 2024-10-16 22:28
@sunannie27 @bonniewolfe 
- Please see the transcription software recommendation in [this comment](https://github.com/hackforla/internship/issues/629#issuecomment-2406132774).
- [TWE: Research: Transcription Software Comparison](https://docs.google.com/spreadsheets/d/1i9hhAzuf6jJNVeAMcjFaxDyC-PE1ImNHpeK002NouSk/edit?gid=0#gid=0) has more detailed information when comparing different software.
- TWE project's transcription needs are identified in #630. See [comment](https://github.com/hackforla/internship/issues/630#issuecomment-2418063462). 
- We can discuss more at the all team meeting to make a decision on the tool we should use.

**Comment by pandanista** [comment] 2024-10-17 17:41
- We will use TurboScribe's free version for transcribing the interviews under 30 mins as the free version allows. 
    - We will keep track of how long each interview transcription takes, so we get a better idea how much time it takes.
- When moving to transcribe interviews over 30 mins, we will decide between otter or turboscribe.

**Comment by mh-faraji** [comment] 2024-10-17 21:47
@pandanista @ExperimentsInHonesty Here are my updates after trying these three software: MacWhisper has no restrictions, but the downside is that its transcripts require a lot of time to clean up. The output is a single block of text, with sentences running together without identifying speakers or including timestamps. TurboScribe/Free allows you to download transcripts with a free account, but the issue is that it doesn’t label speakers or provide timestamps, making the clean-up process equally time-consuming. Otter.ai offers a better solution, as its transcripts include both speaker identification and timestamps. However, the free version doesn’t allow you to download the transcription, and needs a subscription, which costs $16.99 per month.

**Comment by mh-faraji** [comment] 2024-10-17 22:11
I forgot to mention that Otter.ai also offers audio synced with the transcript, which will significantly aid in cleaning up the transcription.

**Comment by mh-faraji** [comment] 2024-10-18 20:24
@pandanista @ExperimentsInHonesty New update: I contacted Turboscribe’s customer service, and they mentioned an Advanced Export option that identifies speakers and includes timestamps. This feature appears to be available for the Free option as well. I tested it on a short YouTube video using a free account, and the transcription I downloaded included both speaker identification and timestamps. Yingjie, could you please assign an issue to me so I can start testing a few interviews and evaluate the transcription output?

**Comment by pandanista** [comment] 2024-10-22 02:14
@mh-faraji Thank you so much for the thorough updates. 

- Sounds like you have tried out a few of them. Do you have the .txt files from your trials? Would you please add them into the [transcription software samples folder](https://drive.google.com/drive/folders/1nLbv8lsw0sb61Hq2QEVS6A0fZXTTf4v-?usp=drive_link)?


- Next steps: I just assigned you to #628 to test the updated issue template draft for the set-up phase before transcribing. 
    - As discussed at 10/17's all team meeting, we have decided to [divide the transcribe template into two templates in sequence](https://github.com/hackforla/internship/issues/335#issuecomment-2420093065). The first one is for set-up, and the second one is for transcribing. We are testing those templates in that order as well.

**Comment by pandanista** [comment] 2024-10-23 02:17
As further discussed at the UXR meeting on 10/22, we decided to try out both Otter's free and TurboScribe's free version on the same interview recording to compare the transcript output quality so we can make a more informed decision on the transcription software.

The transcribing testing issues are created:
- #632 
- #634

**Comment by ExperimentsInHonesty** [comment] 2024-10-31 16:50
We decided to use TurboScribe, since we do not need the AI features of Otter AI.

**Comment by ExperimentsInHonesty** [comment] 2024-10-31 16:53
I moved this issue back to in progress.  I think you write a decision record for the wiki and then we can close this issue out.

Here is the template for the Decision Record

```
This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted).

#### Issue 
#### Problem Statement
#### Potential Solution
#### Feasibility Determination
```

On this page in the [Records section](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted#records) you can find examples of decision records for the website team

**Comment by pandanista** [comment] 2024-11-14 19:57
@bonniewolfe 
Since we don't have a decision record wiki page for TWE, we created [a decision record page](https://github.com/hackforla/internship/wiki/Decision-Records-on-Solutions-Adopted) and [DR: Transcription software choice](https://github.com/hackforla/internship/wiki/DR:-Transcription-software-choice) page using the examples from the website team.

If everything looks good, we can close the issue.

**Comment by KC-skc** [comment] 2024-11-21 17:41
Decision record has been accepted by product.

**Closed by KC-skc** 2024-11-21 17:41 UTC
Labels: role: UI/UX research, size: 1pt, time sensitive, complexity: small, feature: recording transcription, Participant Type: TWE Team Member, Ready for product
