### ISSUE TITLE
Publish Design System Draft to Github pages

### ISSUE THREAD

**Issue by joshfishman** [hackforla/internship#485] opened 2023-10-17 20:51 UTC
### Overview
We need to change the settings of our repo so that we can publish our in progress work on the microsite

### Action Items
- [x] Get repo access (Josh now has admin access)
- [ ] Publish Site to github pages

### Resources/Instructions
[Github Pages Quickstart](https://docs.github.com/en/pages/quickstart)

**Comment by ExperimentsInHonesty** [comment] 2023-10-26 17:19
We decided to create a new repo https://github.com/hackforla/internship-website-design-system, so that the new repository can have ghpages to display the content of the draft design system.

@joshfishman will write a draft of the readme for the new repo.

**Comment by ExperimentsInHonesty** [comment] 2024-04-25 17:23
Tyler needs admin access

**Comment by ExperimentsInHonesty** [comment] 2024-04-25 17:28
- Closing this issue as unplanned because it's a duplicate of https://github.com/hackforla/internship/issues/561

**Closed by ExperimentsInHonesty** 2024-04-25 17:28 UTC
Labels: role: Product, feature: missing, size: 0.25pt, Participant Type: TWE Team Member, Participant Type: HfLA Team member, complexity: missing
